// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzpMGStRu_uLvVAPR-DV0tJTLhmwJVyV0',
    appId: '1:32801833028:android:0874a157190380c1d27c11',
    messagingSenderId: '32801833028',
    projectId: 'todo-list-provider-e2a8c',
    storageBucket: 'todo-list-provider-e2a8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcN7aboePAJFK7Cg1Qt8Vz1tNSi9Ym5PI',
    appId: '1:32801833028:ios:a320699e4a815766d27c11',
    messagingSenderId: '32801833028',
    projectId: 'todo-list-provider-e2a8c',
    storageBucket: 'todo-list-provider-e2a8c.firebasestorage.app',
    androidClientId: '32801833028-m3a1rgktpc4fu86d2rgaa0aeenc4j21e.apps.googleusercontent.com',
    iosClientId: '32801833028-njckuco482fg4bm4vf8ic2kh9je40a3v.apps.googleusercontent.com',
    iosBundleId: 'br.com.academiadofluter.todoListProviders',
  );

}